### ISSUE TITLE
Why is the CBC padding on ODC-INJECTION_DETCHAR so large?

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/veto-definitions#2]
The CBC veto definer files, at least the [ER8 veto definer](https://github.com/ligovirgo/veto-definitions/blob/2bf9ee2bd8ae28684e38826177aa9d50aed15986/cbc/ER8/H1L1-ER8_CBC_OFFLINE.xml) has a +-16-second padding on the detchar safety injections (`ODC-INJECTION_DETCHAR:1`).

Why is the padding so large? Can it safely be reduced to +-1-second?

**Comment by andrew-lundgren** [comment]
No, it's needed. Detchar injections are loud and can produce triggers at least 8 seconds away from time of injection. Also, because they are a number of isolated injections, the flag can turn off between them but we want to veto everything. We lose a little extra time, but these are infrequent. Can revisit once O1 injection plan in place.
